packages:
- '.'
- ../glfw-pal
- ../gl-pal
- ../linear-extra
- ../lens-extra
- ../halive
resolver: nightly-2016-07-07
extra-deps:
- GLFW-b-1.4.8.0
- inline-c-cpp-0.1.0.0
- bindings-GLFW-3.1.2.0
allow-newer: true
